# Generated by Django 3.2.8 on 2021-11-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200)),
                ('server', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=500)),
                ('itemsQuantity', models.CharField(max_length=500)),
                ('finalPrice', models.FloatField()),
                ('NameUser', models.CharField(max_length=100)),
                ('ContactWay', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='offerLimit',
            field=models.IntegerField(default=0),
        ),
    ]
