# Generated by Django 3.2.8 on 2021-11-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0002_auto_20211103_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerrequest',
            old_name='items',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='offerrequest',
            old_name='itemsQuantity',
            new_name='itemQuantity',
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='Status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
