# Generated by Django 3.2.8 on 2021-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0003_auto_20211104_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrequest',
            name='Status',
            field=models.IntegerField(),
        ),
    ]
