# Generated by Django 3.2.8 on 2021-11-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StaffApp', '0005_offerrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerrequest',
            name='ContactWay',
        ),
        migrations.RemoveField(
            model_name='offerrequest',
            name='NameUser',
        ),
        migrations.RemoveField(
            model_name='offerrequest',
            name='game',
        ),
        migrations.RemoveField(
            model_name='offerrequest',
            name='server',
        ),
        migrations.RemoveField(
            model_name='offerrequest',
            name='user',
        ),
        migrations.CreateModel(
            name='OffersRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameUser', models.CharField(max_length=100)),
                ('ContactWay', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=200)),
                ('server', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offersrequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StaffApp.offersrequest'),
        ),
    ]
