# Generated by Django 3.2.8 on 2021-11-12 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StaffApp', '0007_auto_20211112_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerrequest',
            name='offer',
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='ContactWay',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='NameUser',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='Status',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='game',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='server',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offersrequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OffersRequest',
        ),
    ]
