# Generated by Django 3.2.8 on 2021-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0008_auto_20211112_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequest',
            name='ingamename',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='note',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
