# Generated by Django 3.2.8 on 2021-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffApp', '0009_auto_20211112_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequest',
            name='idgame',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='iditem',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='idserver',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
