# Generated by Django 3.2.8 on 2021-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='IDDiscord',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bankId',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
