# Generated by Django 3.2.8 on 2021-11-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_auto_20211112_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bankIdOwner',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
